create table USER_REGISTRATION (
	ID NUMBER(10) NOT NULL PRIMARY KEY ,
	FIRST_NAME VARCHAR(255) not NULL,
	LAST_NAME VARCHAR(255) not NULL,
	COMPANY VARCHAR(255) not NULL,
	ADDRESS VARCHAR(255) not NULL,
	CITY VARCHAR(255) not NULL,
	STATE VARCHAR(255) not NULL,
	ZIP VARCHAR(255) not NULL,
	COUNTY VARCHAR(255) not NULL,
	URL VARCHAR(255) not NULL,
	PHONE_NUMBER VARCHAR(255) not NULL,
	FAX VARCHAR(255) not NULL
);